POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Super Admin Blog",
    "author": "Super Admin",
    "url": "example.com",
    "likes": 420,
    "userId": "69ca700a7cf8bf66352a1feb"
}