POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiaWQiOiI2OWNhYTFkN2QxZWM4MGVhYTg3YmMzNGIiLCJpYXQiOjE3NzQ4ODc2Mzh9.iJMjV07J6qsiPpgYYrP-hkvG8_rkjJh2Ae1WmNarLqM

{
    "title": "Esimerkillinen blogi",
    "author": "Esi Merkkinen",
    "url": "example.com",
    "likes": 100,
    "userId": "69caa1ecd1ec80eaa87bc34d"
}